### ISSUE TITLE
difference between URL & URI

### ISSUE THREAD

**Issue by javax4u** [javax4u/interview-questions#22]
Please describe in 100 to 200 words and put one picture about it

**Comment by apoorvpandey-ap** [comment]
![image](https://user-images.githubusercontent.com/66588814/140928090-f83d5b50-d5ba-494d-af6d-3ce4a1284d68.png)

**Comment by apoorvpandey-ap** [comment]
अपूर्व पाण्डेय
यही मेरा नाम है, जो मेरी पहचान है। यह एक URI की तरह है, लेकिन URL नहीं हो सकता, क्योंकि यह आपको मेरे स्थान या मुझसे संपर्क करने के तरीके के बारे में कुछ नहीं बताता है। इस मामले में अकेले भारत में कम से कम 5 अन्य लोगों की पहचान करना भी होता है।

नालंदा कॉलोनी पटना
यह एक लोकेटर है, जो उस भौतिक स्थान के लिए एक पहचानकर्ता है। यह एक URL और URI दोनों की तरह है (चूंकि सभी URL or URI हैं), और मुझे परोक्ष रूप से "निवासी .." के रूप में भी पहचानता है। इस मामले में यह विशिष्ट रूप से मेरी पहचान करता है, लेकिन अगर मुझे रूममेट मिल जाए तो यह बदल जाएगा।

**Comment by javax4u** [comment]
@apoorvpandey-ap **Can URL be a subset of URI ?**

![image](https://user-images.githubusercontent.com/2442530/141458583-2ffbfb56-9cda-427f-89dd-55c24790b5df.png)

**Comment by jkumar0021** [comment]
Could you please  adorate the URL and URI its confusing to me

**Comment by apoorvpandey-ap** [comment]
[Reference  Link](https://www.youtube.com/watch?v=-mSrNVki_hc&list=LL)

**Comment by javax4u** [comment]
> Yes, URL can be subset of URI because URI have two subset

Your answer is correct. URI = URN + URL

but your reference video link is not good. please follow wikipedia or ietf links for good reading.  There are many persons uploading video on youtube and blog you can bring up Namibia video link and say THIS GUY says this. :) :) 
So Rashmi Singh is very bad reference link.
