### ISSUE TITLE
HashMap vs Concurrent-HashMap

### ISSUE THREAD

**Issue by javax4u** [javax4u/interview-questions#24]
- [x] Q. Can we pass null key in both maps ?
- [x] Q. Define difference between them in tabular format ?
- [x] Q. ConcurrentHashMap was it generated after java 1.5 ?
- [x] #28

**Comment by jkumar0021** [comment]
![image](https://user-images.githubusercontent.com/809650/141248747-942f9af5-a613-4d9c-aff3-34a4cb4c1ed5.png)
