### ISSUE TITLE
Q. Can we delete a record while iterating HashMap ? Write an example if you say yes.

### ISSUE THREAD

**Issue by javax4u** [javax4u/interview-questions#28]

**Comment by jkumar0021** [comment]
![image](https://user-images.githubusercontent.com/809650/140488628-6640c43f-c1fa-43da-94a6-fd7e0a464527.png)

![image](https://user-images.githubusercontent.com/809650/140488782-cd6dbea5-5944-441a-8d32-f4b430b7cb46.png)
