### ISSUE TITLE
what is the o/p of the below code   

### ISSUE THREAD

**Issue by apoorvpandey-ap** [javax4u/interview-questions#31]
class TestApp {
public static void main(String args[]) {
int odd = 1;
if (odd) {
System.out.println("odd");
}
else {
System.out.println("even"); }
}
}
}

**Comment by apoorvpandey-ap** [comment]
class TestApp { 
        public static void main(String args[]) {
                int odd = 1; 
                if (odd) {
                        System.out.println("odd"); 
                        } 
                else {
                        System.out.println("even"); } 
                        } 
        }
}

**Comment by javax4u** [comment]
This code will throw compiler error on line if(odd) because it's not boolean.

**Comment by jkumar0021** [comment]
This code will give the compiled time exception, Because in Java if condition will work on boolean check and in the above code we are passing int value, so compiler will not allow.
