### ISSUE TITLE
HashTable and concurrent Hash Map difference

### ISSUE THREAD

**Issue by apoorvpandey-ap** [javax4u/interview-questions#58]

**Comment by javax4u** [comment]
| Difference | HashTable | ConcurrentHashMap|
| ------------|-------------|-----------------------|
| Thread Safe| Only One Thread can access at a time | Multiple Thread can access at a time|
| Locking| All buckets will be locked | Only selected buckets will be locked. By default 16|
| Update| User can not delete an entry at iteration time| User can delete an entry|
| ConcurrentModificationException| Yes| No It's safe.|
