### ISSUE TITLE
Step function vs Lambda

### ISSUE THREAD

**Issue by apoorvpandey-ap** [javax4u/interview-questions#83]

**Comment by jkumar0021** [comment]
Lambda and Step functions are like floors and steps to each floor. You cannot replace one with another.
AWS Lambda is an event-driven, serverless computing platform provided by Amazon as a part of Amazon Web Services.  Lambda is computing, steps functions take them to the desired step.
Step functions are excellent at coordinating workflows that involve multiple predefined steps. It can do parallel tasks and error handling well. It mainly uses Lambda functions to perform each task.

![image](https://user-images.githubusercontent.com/809650/141253541-f1461254-3510-4d42-aadc-71ac1c40251e.png)
